Revisi 20230512
eriklukiman/balistars2_old pull request #1
Opened 2023-05-12 03:07 UTC by TempatKitaSoftware

Perubahan :

- Perubahan Tampilan Progress Bar
- Template Form Surat Pengajuan
- Ubah Label Input dari "Profit" Menjadi "Margin Profit" di Form Pengajuan Additional
- Tambah Fitur Notifikasi
- Tambah Laporan Report Performa (Laporan Poin Pengajuan)
- Tambah Include Laba Rugi Kotor di Master Data Penyesuaian

2023-05-12 16:13 UTC, eriklukiman requested changes

2023-05-12 16:13 UTC, eriklukiman commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/Exception.php';
don't use hardcode in here. use $BASE_URL_HTML instead

2023-05-12 16:13 UTC, eriklukiman commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/PHPMailer.php';
same here

2023-05-12 16:13 UTC, eriklukiman commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/SMTP.php';
same here

2023-05-13 07:45 UTC, TempatKitaSoftware commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/Exception.php';
Okay, i will fix it

2023-05-13 07:45 UTC, TempatKitaSoftware commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/PHPMailer.php';
Okay, i will fix it

2023-05-13 07:45 UTC, TempatKitaSoftware commented on system/proses/automailer.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/balistars2/assets/vendor/PHPMailer/src/SMTP.php';
Okay, i will fix it

2023-05-13 08:00 UTC, TempatKitaSoftware commented on system/laporan/laporan_poin_pengajuan/.DS_Store
Okay, i will remove it

2023-05-16 08:01 UTC, merged